### PR TITLE
Replaced LockScreen with a new, Intel compatible version

### PR DESCRIPTION
**Pull request by Sesquipedalian**
This replaces the LockScreen binary that was build for PPC with a new, Intel compatible version. The code for the binary is from https://github.com/gaomd/lock-screen-app/blob/master/main.m. This is identical to the code discussed in https://groups.google.com/forum/#!topic/blacktree-quicksilver/dn1sBhlaWug

### CODE REVIEW

**Comment by pjrobertson** [comment]
Did you just build this in Xcode then copy it to the project?

**Comment by pjrobertson** [comment]
Aaah I see the SO question at https://apple.stackexchange.com/questions/80058/lock-screen-command-one-liner

It would be nice to include this code in the project for future builds. I'll test it out in a little while. Thanks @Sesquipedalian :-)

**Comment by skurfer** [comment]
> It would be nice to include this code in the project for future builds.

I like that idea. I was going to merge this and the other, then clean them up, but there’s plenty to do with just that one, so I’ll leave this open.

**Comment by Sesquipedalian** [comment]
I just went with the easiest solution, @pjrobertson. Since this plugin has always just included a LockScreen binary as a resource, dropping in a new, working binary in its place seemed like the simplest way to go. If you'd rather bake the code into the plugin itself, go for it. 

I think, though, that it might make more sense to leave it as a bundled binary. This code depends on the keychain.menu item, and there's no guarantee that that will always remain available in its current form. Keeping this function in its own little binary would prevent any problems from arising with the plugin itself if Apple ever does change it. The worst that could happen would be that the running LockScreen would fail silently, just like it does now. If the code were baked in, QS itself would throw an error.

**Comment by pjrobertson** [comment]
> I think, though, that it might make more sense to leave it as a bundled binary.

I just meant that the code was included in the project and used to build the standalone plugin. Not that the code itself was included in Quicksilver.

Anyway, I've created #3 which builds on this, and hopefully will be easier to merge (no conflicts)

**Comment by Sesquipedalian** [comment]
Oh, I see. Sounds good, then.

**Comment by pjrobertson** [comment]
Thanks very much for the work though Jon! We always appreciate others helping out :-)

**Pull request closed without merging**
