### PR TITLE
Add AirDrop/Bluetooth/ScreenSaver/SwitchUser scripts; Remove LockScreen which is ppc-only

### PR DESCRIPTION
**Pull request by du-song**

### CODE REVIEW

**Comment by skurfer** [comment]
Thanks for the updates. Some observations:
- You can remove "Sync Now" too, since iSync is no longer available.
- As we update plug-ins now, we've also been making sure they have complete documentation. The standard way to do this is to put it in a file called `Documentation.mdown` and let `bltrversion` update the `Info.plist` when you build. I would just create a [definition list](http://pythonhosted.org/Markdown/extensions/definition_lists.html) showing each script and a short summary of what it does. See http://projects.skurfer.com/QuicksilverPlug-inReference.mdown#documentation-and-bltrversion
- For that to work, you'll need to add a build phase for `bltrversion`. See http://projects.skurfer.com/QuicksilverPlug-inReference.mdown#plug-in-clean-up-and-modernization
- The Bluetooth toggle depends on `blueutil`. At the very least, we should mention that in the documentation. It should also be possible to pop up an alert if it's missing. But the best option would be to ask @toy for permission to just bundle it with the plug-in.
- The build number and version need to be increased. `bltrversion` will do the build number automatically (sometimes annoyingly so), but you'll need to increase the human-readable version manually.

**Comment by toy** [comment]
Original `blueutil` was created by Frederik Seiffert and [is public domain](http://www.frederikseiffert.de/blueutil/), I just added some features. So free to be bundled/integrated/included in plug-in. I am glad to help even indirectly with the tool I use every day!

**Comment by skurfer** [comment]
Thanks for getting back to us so quickly, @toy.

So, there’s our answer.

**Comment by pjrobertson** [comment]
Wow only just noticed this. It'd be nice to get this out there. @freewizard is there a replacement script for the "Lock Screen" script. It'd be nice not to lose that, but of course it's not a requirement.

If the things Rob mentioned are too confusing (Plugin management can be) I'd be happy to do that. The only thing that really needs doing is:
- Packaging blueutil with the plugin
- Adding documentation

Thanks!

**Comment by iandol** [comment]
You can lock the screen with the following applescript (to replace the broken binary):

``` applescript
do shell script "/System/Library/CoreServices/Menu\\ Extras/User.menu/Contents/Resources/CGSession -suspend"
```

**Pull request merged**
