### PR TITLE
M1 Recompile

### LINKED ISSUE #2636: Sleep no longer selectable
The Sleep function is no longer available to the input.

### PR DESCRIPTION
**Pull request by pjrobertson**
I took @n8henrie 's branch and squashed and tidied the commits. Wanted to make a PR for us to discuss, instead of doing it on the issue itself and giving people a ton of noise. This should be good to go, I assume? 

We can build and quickly fix quicksilver/quicksilver#2636

### CODE REVIEW

**Comment by n8henrie** [comment]
@pjrobertson what does `Toggle Audio Output.scpt` do / what is it supposed to do?

I assume it's supposed to toggle the output destination? If so is it supposed to toggle it back when run a second time?

I have 2 output destinations available -- my MBP and an Apple TV. It does nothing if the MBP is selected for output. If I have the Apple TV selected as output destination, it switches to my MBP, but then never switches back when run again.

Is this intended behavior AFAYK?

**Comment by n8henrie** [comment]
Hmmm, while testing for https://github.com/quicksilver/Quicksilver/pull/2647 it looks like something in this PR is messing up codesigning.

```console
$ codesign -vvv --force --sign - ./Extra\ Scripts\ Plugin.qsplugin
./Extra Scripts Plugin.qsplugin: bundle format unrecognized, invalid, or unsuitable
```

**Comment by n8henrie** [comment]
`Lock Screen.app` disappeared. Was previously created from https://github.com/gaomd/lock-screen-app/tree/636d9c6720f5b4cdf547ff14a827de4ac67c9c39 via `osacompile -o 'Lock Screen.app' 'Lock Screen.applescript'`.

Currently it's just a compiled binary that needs to be run -- perhaps we can get rid of the `.app` bundle stuff?

**Comment by n8henrie** [comment]
> it looks like something in this PR is messing up codesigning.

Now fixed.

> This should be good to go, I assume?

I think so

**Comment by skurfer** [comment]
I had a bunch of updates locally that I never merged/pushed. 🤦🏻‍♂️ I’ll resolve the conflicts between this and that and get a new release out hopefully in the next couple of days.

**Comment by pjrobertson** [comment]
> I had a bunch of updates locally that I never merged/pushed. 🤦🏻‍♂️ I’ll resolve the conflicts between this and that and get a new release out hopefully in the next couple of days.

Happens to us all! I wonder how much un-commited code I have lying around 🤦  Sounds good on the release.

**Pull request merged**
